<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="3.1.31" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LinkedUp.Api.Tests" />
    <ProjectReference Include="../LinkedUp.Contracts/LinkedUp.Contracts.csproj" />
    <ProjectReference Include="../LinkedUp.Simulation/LinkedUp.Simulation.csproj" />
  </ItemGroup>

</Project>
